// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace VirtualSomML.Model
{
    public class ModelInput
    {
        [ColumnName("description"), LoadColumn(0)]
        public string Description { get; set; }


        [ColumnName("label"), LoadColumn(1)]
        public string Label { get; set; }


    }
}
